# Generated by Django 6.0.3 on 2026-03-23 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_category_is_system_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_system",
        ),
    ]
